### ISSUE TITLE
[ci] Some tests are failing with out of space errors

### ISSUE THREAD

**Issue by prabhu** [owasp-dep-scan/dep-scan#248]
### Expected Behavior

Some tests are failing.

### Actual Behavior

```
 INFO [2024-02-13 09:56:57,042] About to download the vulnerability database from ghcr.io/appthreat/vdbxz:v5. This might take a while ...
INFO [2024-02-13 09:57:26,615] Performing regular scan for rocket.chat@sha256:379f7afa0e67497c363ac9a9b3e7e6a6d31deee228233307c987e4a0c68b28e6 using plugin universal
INFO [2024-02-13 09:57:40,965] To improve performance, cache the bom file and invoke depscan with --bom /home/runner/work/dep-scan/dep-scan/containertests_ubuntu-latest/sbom-yaml-universal.json instead of -i
OSError: [Errno 28] No space left on device
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/dep-scan/dep-scan/depscan/cli.py", line 1101, in <module>
    main()
  File "/home/runner/work/dep-scan/dep-scan/depscan/cli.py", line 1064, in main
    console.save_html(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/rich/console.py", line 2275, in save_html
    with open(path, "wt", encoding="utf-8") as write_file:
OSError: [Errno 28] No space left on device
```

**Comment by prabhu** [comment]
There seems to be a `/mnt` drive on Linux agents. Perhaps we can suggest this via our docs for users struggling to run depscan on github hosted agents.

```
Run df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   35G   38G  48% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
total 4.1G
-rw-r--r-- 1 root root  333 Feb 13 13:18 DATALOSS_WARNING_README.txt
drwx------ 2 root root  16K Feb 13 13:18 lost+found
-rw------- 1 root root 4.0G Feb 13 13:18 swapfile
```
