### ISSUE TITLE
Bug: AttributeError: 'lief._lief.ELF.DynamicEntryRunPath' object has no attribute 'name'   

### ISSUE THREAD

**Issue by aryan-rajoria** [owasp-dep-scan/dep-scan#354]
### Expected Behavior

No error message should be produced.

### Actual Behavior

Produces error message:
```
(blint) ➜  tensorflow_open blint sbom -i ./tensorflow/libtensorflow_cc.so.2 --deep -o sbom_deep 
Processing ~/tensorflow_open/tensorflow/libtensorflow_cc.so.2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00[16:24:00] ERROR    Caught <class 'AttributeError'>: 'lief._lief.ELF.DynamicEntryRunPath' object has no attribute 'name' while parsing              
                    /tensorflow_open/tensorflow/libtensorflow_cc.so.2.                                            
                    Traceback (most recent call last):                                                                                              
                      File "~/miniconda3/envs/blint/lib/python3.12/site-packages/blint/binary.py", line 750, in parse                 
                        metadata = add_elf_metadata(exe_file, metadata, parsed_obj)                                                                 
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 
                      File "~/miniconda3/envs/blint/lib/python3.12/site-packages/blint/binary.py", line 809, in add_elf_metadata      
                        metadata = add_elf_dynamic_entries(dynamic_entries, metadata)                                                               
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
                      File "~/miniconda3/envs/blint/lib/python3.12/site-packages/blint/binary.py", line 920, in                       
                    add_elf_dynamic_entries                                                                                                         
                        "name": demangle_symbolic_name(entry.name),                                                                                 
                                                       ^^^^^^^^^^                                                                                   
                    AttributeError: 'lief._lief.ELF.DynamicEntryRunPath' object has no attribute 'name'     
```

### Steps to Reproduce

Running on certain binaries we can see blint produce this error. 
Steps:
1) create new conda environment with python=3.12
2) install blint using: `pip install blint`
3) download tensorflow 2.17.0 .whl file from pypi and extract it
4) in tensorflow .whl archive there is `libtensorflow_cc.so.2` on which we run blint.

**Comment by prabhu** [comment]
@aryan-rajoria can you raise this under the blint repo please?
