### ISSUE TITLE
Bug: Downloading vulnerability database sometimes fails with ProtocolError/ChunkedEncodingError

### ISSUE THREAD

**Issue by gcatto** [owasp-dep-scan/dep-scan#361]
### Expected Behavior

We have created GitLab CI jobs to run dep-scan against some of our projects. It runs and generates reports, as expected, most of the time.

### Actual Behavior

However, sometimes it fails when trying to download the vulnerability database from ghcr.io/appthreat/vdbgz:

```
INFO [2024-11-01 12:24:06,660] About to download the vulnerability database from ghcr.io/appthreat/vdbgz:v5. This might take a while ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/response.py", line 748, in _error_catcher
    yield
  File "/usr/local/lib/python3.12/site-packages/urllib3/response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(1[70](https://URL/jobs/282591#L70)54016 bytes read, 213467088 more expected)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.12/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/response.py", line 977, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/response.py", line 8[72](https://URL/jobs/282591#L72), in _raw_read
    with self._error_catcher():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/urllib3/response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(17054016 bytes read, 213467088 more expected)', IncompleteRead(17054016 bytes read, 213467088 more expected))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/depscan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/depscan/cli.py", line 1018, in main
    paths_list = download_image()
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/depscan/lib/orasclient.py", line 128, in download_image
    paths_list = oras_client.pull(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oras/client.py", line 138, in pull
    return self.remote.pull(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oras/provider.py", line 8[73](https:/URL/jobs/282591#L73), in pull
    self.download_blob(container, layer["digest"], outfile)
  File "/usr/local/lib/python3.12/site-packages/oras/decorator.py", line 35, in __call__
    return self.func(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oras/provider.py", line 473, in download_blob
    raise e
  File "/usr/local/lib/python3.12/site-packages/oras/provider.py", line 465, in download_blob
    for chunk in r.iter_content(chunk_size=8192):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(17054016 bytes read, 213467088 more expected)', IncompleteRead(17054016 bytes read, 213467088 more expected))
```

### Additional Information

I can rerun the jobs and they'll usually pass, but it does creates unnecessary failures. I was hoping you might have some guidance on what could be done about it. Thanks!

**Comment by prabhu** [comment]
Must be some rate-limiting from GitHub. You can try setting a read-only GITHUB_TOKEN to see if it helps. Alternatively, you can maintain a local GitLab clone of the databases. Refer to the workflows in this repo for some ideas

https://github.com/AppThreat/vdb

**Comment by gcatto** [comment]
Okay, thank you the the help and ideas!

**Comment by gcatto** [comment]
@prabhu following up on this front: is there a way to tell dep-scan to use an existing database (at some path or what not), instead of having to download it from somewhere? I couldn't find a way to do it in the docs or trying to search the code a little bit.

**Comment by prabhu** [comment]
You can set the directory using VDB_HOME environment variable

**Comment by gcatto** [comment]
I used oras to get the threat database:
```
oras pull ghcr.io/appthreat/vdbgz:v5 -o $VDB_HOME
```
I then unpacked them so I had `data.vdb5` and `data.index.vdb5` in my `$VDB_HOME`. When I run `depscan` though, it still does this:
```
About to download the vulnerability database from ghcr.io/appthreat/vdbgz:v5. This might take a while ...
```
Am I overlooking a key step or config? Thanks!

**Comment by gcatto** [comment]
@prabhu I just wanted to follow-up on this front. Thanks!

**Comment by prabhu** [comment]
@gcatto There are no open tickets, so must be a devops thing. Can you check if VDB_HOME is set and passed to any container images correctly?

**Comment by gcatto** [comment]
@prabhu I am just trying to get it working locally with a container on my machine, before doing any fancier stuff. I have an image that starts from `ghcr.io/cyclonedx/cdxgen` and pip installs `owasp-depscan`. I am trying to use that image to mount the project code and the VDB content:
```
C:\dev>docker run --rm -it -v C:/dev/vdb:/src/vdb -v C:/dev/app:/src/app <image>
[root@def415e34741 /]# VDB_HOME=/src/vdb
[root@def415e34741 /]# echo VDB_HOME=$VDB_HOME
VDB_HOME=/src/vdb
[root@def415e34741 /]# ls $VDB_HOME
data.index.vdb5  data.index.vdb5.tar  data.index.vdb5.tar.gz  data.index.vdb6.zst  data.vdb5  data.vdb5.tar  data.vdb5.tar.gz  data.vdb6.zst  vdb.meta
[root@def415e34741 /]# cd /src/app
[root@def415e34741 app]# depscan --src . --reports-dir ./dep-scan-reports --no-banner --explain --debug --type js
DEBUG [2024-12-05 13:49:34,125] ⚡︎ Executing "cdxgen -r -t js -o ./dep-scan-reports/sbom-js.json --profile generic /src/app"
DEBUG [2024-12-05 13:49:44,885]
DEBUG [2024-12-05 13:49:44,887] Scanning using the bom file ./dep-scan-reports/sbom-js.json
INFO [2024-12-05 13:49:44,887] To improve performance, cache the bom file and invoke depscan with --bom ./dep-scan-reports/sbom-js.json instead of -i
╭─────────────────── Risk Audit Capability ───────────────────╮
│ Depscan supports OSS Risk audit for this project.           │
│ To enable set the environment variable ENABLE_OSS_RISK=true │
╰─────────────────────────────────────────────────────────────╯
DEBUG [2024-12-05 13:49:44,906] Performing remote audit for /src/app of type js
DEBUG [2024-12-05 13:49:44,906] No of packages 990
DEBUG [2024-12-05 13:49:45,343] Remote audit yielded 3 results
INFO [2024-12-05 13:49:45,344] About to download the vulnerability database from ghcr.io/appthreat/vdbgz:v5. This might take a while ...
```

**Comment by prabhu** [comment]
Mixing Windows volume path with Linux ones is a new scenario for us. We won't have time to look at this in December. Can you run it from linux or fully linux based volume mounts?

**Comment by gcatto** [comment]
If I use git bash on Windows, I can do it this way, is that what you meant? Thanks!
```
$ docker run --rm -it -v //c/dev/vdb:/src/vdb -v //c/dev/app:/src/app <image>
[root@117b8b388c01 /]# VDB_HOME=/src/vdb
[root@117b8b388c01 /]# echo VDB_HOME=$VDB_HOME
VDB_HOME=/src/vdb
[root@117b8b388c01 /]# ls $VDB_HOME
data.index.vdb5  data.index.vdb5.tar  data.index.vdb5.tar.gz  data.index.vdb6.zst  data.vdb5  data.vdb5.tar  data.vdb5.tar.gz  data.vdb6.zst  vdb.meta
[root@117b8b388c01 /]# cd /src/app
[root@117b8b388c01 app]# depscan --src . --reports-dir ./dep-scan-reports --no-banner --explain --debug --type js
DEBUG [2024-12-05 14:05:04,851] ⚡︎ Executing "cdxgen -r -t js -o ./dep-scan-reports/sbom-js.json --profile generic /src/app"
DEBUG [2024-12-05 14:05:16,298]
DEBUG [2024-12-05 14:05:16,301] Scanning using the bom file ./dep-scan-reports/sbom-js.json
INFO [2024-12-05 14:05:16,301] To improve performance, cache the bom file and invoke depscan with --bom ./dep-scan-reports/sbom-js.json instead of -i
```

**Comment by prabhu** [comment]
Use the export prefix when setting the directory. `export VDB_HOME=/src/vdb`.

Also pass `-e VDB_HOME=/src/vdb` in the docker run command.

**Comment by gcatto** [comment]
Oh yes, using `-e` or `export` got things working, and it works from the Windows `docker run` command that way too, thanks!

Last question (I think, hah): do I need both the `vdbgz:v5` and `vdbzst:v6`? Just one? Other?

Thanks for all the help!

**Comment by prabhu** [comment]
v6 is not released yet, but feel free to test the master branch by adding `:master` tag to the container image. Please share on social media if you notice any performance difference.
